#!/usr/bin/env bash
set -euo pipefail

# scaffold-init.sh
# one-shot: 프로젝트에 .hermes scaffold 설치 + 이름 치환 + (옵션) cron 등록
#
# 예시:
#   bash scaffold-init.sh --project-dir ~/dev-private/lore --repo c-yeonwoo/lore
#   bash scaffold-init.sh --project-dir ~/dev-private/lore --repo c-yeonwoo/lore --project-name lore --run-cron-setup

usage() {
  cat <<'EOF'
Usage:
  scaffold-init.sh --project-dir <path> --repo <owner/repo> [options]

Required:
  --project-dir PATH      target project root (git repo)
  --repo OWNER/REPO       github repo slug

Options:
  --project-name NAME     default: basename(project-dir)
  --template-dir PATH     default: ~/dev-private/palette/.hermes
  --force                 overwrite existing .hermes
  --run-cron-setup        run target .hermes/cron-setup.sh after generation
  --dry-run               print actions only
  -h, --help
EOF
}

PROJECT_DIR=""
REPO_SLUG=""
PROJECT_NAME=""
TEMPLATE_DIR="$HOME/dev-private/palette/.hermes"
FORCE=0
RUN_CRON=0
DRY_RUN=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --project-dir) PROJECT_DIR="$2"; shift 2 ;;
    --repo) REPO_SLUG="$2"; shift 2 ;;
    --project-name) PROJECT_NAME="$2"; shift 2 ;;
    --template-dir) TEMPLATE_DIR="$2"; shift 2 ;;
    --force) FORCE=1; shift ;;
    --run-cron-setup) RUN_CRON=1; shift ;;
    --dry-run) DRY_RUN=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown arg: $1" >&2; usage; exit 2 ;;
  esac
done

[[ -z "$PROJECT_DIR" || -z "$REPO_SLUG" ]] && { usage; exit 2; }
[[ -d "$PROJECT_DIR" ]] || { echo "❌ project dir not found: $PROJECT_DIR" >&2; exit 1; }
[[ -d "$TEMPLATE_DIR" ]] || { echo "❌ template dir not found: $TEMPLATE_DIR" >&2; exit 1; }

if [[ -z "$PROJECT_NAME" ]]; then
  PROJECT_NAME="$(basename "$PROJECT_DIR")"
fi
PROJECT_SLUG="${PROJECT_NAME// /-}"
PROJECT_UPPER="$(printf '%s' "$PROJECT_NAME" | tr '[:lower:]-' '[:upper:]_')"
PROJECT_HERMES_DIR="$PROJECT_DIR/.hermes"
PROJECT_PAT_VAR="${PROJECT_UPPER}_AGENT_PAT"

say() { echo "[scaffold] $*"; }
run() {
  if [[ "$DRY_RUN" -eq 1 ]]; then
    echo "DRYRUN: $*"
  else
    eval "$@"
  fi
}

say "project_dir=$PROJECT_DIR"
say "project_name=$PROJECT_NAME"
say "repo=$REPO_SLUG"
say "template=$TEMPLATE_DIR"

if [[ -e "$PROJECT_HERMES_DIR" && "$FORCE" -ne 1 ]]; then
  echo "❌ $PROJECT_HERMES_DIR already exists. Use --force to overwrite." >&2
  exit 1
fi

if [[ "$FORCE" -eq 1 ]]; then
  run "rm -rf \"$PROJECT_HERMES_DIR\""
fi

run "mkdir -p \"$PROJECT_HERMES_DIR\""
run "cp -R \"$TEMPLATE_DIR\"/* \"$PROJECT_HERMES_DIR\"/"

# rename palette-prefixed scripts -> <project>-*
for role in pm executor reviewer; do
  src="$PROJECT_HERMES_DIR/scripts/palette-${role}.sh"
  dst="$PROJECT_HERMES_DIR/scripts/${PROJECT_SLUG}-${role}.sh"
  if [[ -f "$src" ]]; then
    run "mv \"$src\" \"$dst\""
  fi
done

# rename PO skill dir
if [[ -d "$PROJECT_HERMES_DIR/skills/palette-po" ]]; then
  run "mv \"$PROJECT_HERMES_DIR/skills/palette-po\" \"$PROJECT_HERMES_DIR/skills/${PROJECT_SLUG}-po\""
fi

# text substitutions inside scaffold files
if [[ "$DRY_RUN" -ne 1 ]]; then
  python3 - <<PY
from pathlib import Path
p = Path(r"$PROJECT_HERMES_DIR")
repl = {
    "palette-po": f"$PROJECT_SLUG-po",
    "palette-pm": f"$PROJECT_SLUG-pm",
    "palette-executor": f"$PROJECT_SLUG-executor",
    "palette-reviewer": f"$PROJECT_SLUG-reviewer",
    "PALETTE_REPO": "PROJECT_REPO",
    "PALETTE_REPO_CWD": "PROJECT_REPO_CWD",
    "PALETTE_WIP_CAP": "PROJECT_WIP_CAP",
    "PALETTE_AGENT_PAT": "PROJECT_AGENT_PAT",
    "c-yeonwoo/palette": "$REPO_SLUG",
    "~/dev-private/palette": f"$PROJECT_DIR",
    "/tmp/palette-agent-workspaces": f"/tmp/$PROJECT_SLUG-agent-workspaces",
}
for f in p.rglob('*'):
    if not f.is_file():
        continue
    if f.suffix.lower() not in {'.sh', '.md', '.txt', '.yaml', '.yml'}:
        continue
    txt = f.read_text(encoding='utf-8', errors='ignore')
    new = txt
    for a,b in repl.items():
        new = new.replace(a,b)
    if new != txt:
        f.write_text(new, encoding='utf-8')
PY
fi

# add .env hint file
ENV_HINT="$PROJECT_HERMES_DIR/.env.agent-harness.example"
if [[ "$DRY_RUN" -eq 1 ]]; then
  echo "DRYRUN: write $ENV_HINT"
else
  cat > "$ENV_HINT" <<EOF
# Generated by scaffold-init.sh
PROJECT_NAME=$PROJECT_NAME
PROJECT_REPO=$REPO_SLUG
PROJECT_REPO_CWD=$PROJECT_DIR
$PROJECT_PAT_VAR=ghp_xxx
# optional generic fallback
PROJECT_AGENT_PAT=
# LLM
ANTHROPIC_API_KEY=
ANTHROPIC_AUTH_TOKEN=
EOF
fi

# executable bits
run "find \"$PROJECT_HERMES_DIR\" -type f -name '*.sh' -exec chmod +x {} \\;"

say "generated: $PROJECT_HERMES_DIR"
say "next:"
say "  1) source $PROJECT_HERMES_DIR/aliases.sh"
say "  2) export $PROJECT_PAT_VAR=..."
say "  3) (optional) bash $PROJECT_HERMES_DIR/bootstrap.sh"
say "  4) bash $PROJECT_HERMES_DIR/cron-setup.sh"

if [[ "$RUN_CRON" -eq 1 ]]; then
  if [[ "$DRY_RUN" -eq 1 ]]; then
    say "DRYRUN: would run cron-setup"
  else
    (cd "$PROJECT_DIR" && bash "$PROJECT_HERMES_DIR/cron-setup.sh")
  fi
fi

say "done"
